export {default as Home} from "./home"
export {default as About} from "./about"
export {default as Schools} from "./schools"
export {default as Login} from "./login"
export {default as NotFound} from "./notfound"
export {default as Unauthorized} from "./unauthorized"