//auth
export const ADD_AUTH_OBJECT = "ADD_AUTH_OBJECT"
export const REMOVE_AUTH_OBJECT = "REMOVE_AUTH_OBJECT"

//teachers
export const ADD_TEACHERS = "ADD_TEACHERS"
export const REMOVE_TEACHERS = "REMOVE_TEACHERS"
export const ADD_TEACHER = "ADD_TEACHER"
export const REMOVE_TEACHER = "REMOVE_TEACHER"